function deltaH = calcDeltaEntropyISI_allTableRows(R)
% Generate a numerical column vector of delta-H values from the table of
% DirectISI-Entropy values. This function works specifically on the table
% generated by "calcDirectEntropyISIbootstrap_batch.m".

nRows = size(R, 1);

% First get DBS H-estimate for all rows:
HdbsEst = fitLinear_HnOrd_perRow(R.H_DBS);


% Then get PRE-dbs bootstrapped estimate:
Hboot = R.H_PREboot;
Hpre = cell(nRows, 1);
for iRow = 1:nRows
    Hpre{iRow,1} = mean(Hboot{iRow,1}, 1);
    
end

HpreEst = fitLinear_HnOrd_perRow(Hpre);


% Finally, subtract PRE from DBS to get deltaH
deltaH = HdbsEst - HpreEst;



end



%% SUB-FUNCTIONS

function H_Est = fitLinear_HnOrd_perRow(H_multOrd)
% Takes in cell array with each row containing a row-vector of multiorder
% Entropy estimates. Outputs a corresponding column-vector of Entropy
% estimates according to the linear fit method. 

nRows = size(H_multOrd, 1);
H_Est = zeros(nRows, 1);
for iRow = 1:nRows
    H_Est(iRow,1) = fitLinear_HnOrd(H_multOrd{iRow,1});
    
end

end