function deltaH = calcDeltaEntropyISIord1_allTableRows(R)
% Generate a numerical column vector of delta-H values from the table of
% DirectISI-Entropy values. This function works specifically on the table
% generated by "calcDirectEntropyISIbootstrap_batch.m". Note on table
% variable names: It assumes that the isi-based Entropy values are in the
% variable column: "H_DBS"; the isi-based pre-DBS Entropy values are in:
% "H_PREboot"; 

nRows = size(R, 1);

% First get DBS H-estimate for all rows:
H1dbs = extractH1(R.H_DBS);


% Then get PRE-dbs bootstrapped estimate:
Hboot = R.H_PREboot;
HpreCell = cell(nRows, 1);
for iRow = 1:nRows
    HpreCell{iRow,1} = mean(Hboot{iRow,1}, 1);
    
end

H1pre = extractH1(HpreCell);


% Finally, subtract PRE from DBS to get deltaH
deltaH = H1dbs - H1pre;



end



%% SUB-FUNCTIONS

% function H1 = extractH1(H_multOrd)
% % Takes in cell array with each row containing a row-vector of multiorder
% % Entropy estimates. Outputs a corresponding numerical column-vector of
% % first-order Entropy only
% 
% nRows = size(H_multOrd, 1);
% H1 = zeros(nRows, 1);
% for iRow = 1:nRows
%     H1(iRow,1) = H_multOrd{iRow,1}(1,1);
%     
% end
% 
% end

function H_Est = fitLinear_HnOrd_perRow(H_multOrd)
% Takes in cell array with each row containing a row-vector of multiorder
% Entropy estimates. Outputs a corresponding column-vector of Entropy
% estimates according to the linear fit method. 

nRows = size(H_multOrd, 1);
H_Est = zeros(nRows, 1);
for iRow = 1:nRows
    H_Est(iRow,1) = fitLinear_HnOrd(H_multOrd{iRow,1});
    
end

end