function H1pre = extractH1pre(R)
% Extract a numerical column vector of average values from the table of
% DirectISI-Entropy values, taking the average of bootstrapped values. 
% This function works specifically on the table generated by 
% "calcDirectEntropyISIbootstrap_batch.m".

nRows = size(R, 1);

% Then get PRE-dbs bootstrapped estimate:
Hboot = R.H_PREboot;
HpreCell = cell(nRows, 1);
for iRow = 1:nRows
    HpreCell{iRow,1} = mean(Hboot{iRow,1}, 1);
    
end

H1pre = extractH1(HpreCell);





end



%% SUB-FUNCTIONS

% function H1 = extractH1(H_multOrd)
% % Takes in cell array with each row containing a row-vector of multiorder
% % Entropy estimates. Outputs a corresponding numerical column-vector of
% % first-order Entropy only
% 
% nRows = size(H_multOrd, 1);
% H1 = zeros(nRows, 1);
% for iRow = 1:nRows
%     H1(iRow,1) = H_multOrd{iRow,1}(1,1);
%     
% end
% 
% end

function H_Est = fitLinear_HnOrd_perRow(H_multOrd)
% Takes in cell array with each row containing a row-vector of multiorder
% Entropy estimates. Outputs a corresponding column-vector of Entropy
% estimates according to the linear fit method. 

nRows = size(H_multOrd, 1);
H_Est = zeros(nRows, 1);
for iRow = 1:nRows
    H_Est(iRow,1) = fitLinear_HnOrd(H_multOrd{iRow,1});
    
end

end